In [1]:

import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1)
print(arr2)
print(arr3)



[10 20 30]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
import numpy as np

# (Vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)  

# (Matrix / Spreadsheet)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
res = np.dot(a, b)
print(res)

[[19 22]
 [43 50]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3])
lst = [1, 2, 3]
print(arr + 10)

[11 12 13]
